### PR TITLE
Removed git output, added controlled output with locks

### PR DESCRIPTION
**Pull request by diego95root**
Hi, I structured the code a bit in case you import it as a module and changed the git clone output by prints for each repo (it has a lock so that the threads don't interfere with each other). Even though it seems a lot has changed it really isn't like that...

### CODE REVIEW

**Comment by tbalz2319** [comment]
Hey thanks this looks really great! I will test it out tonight and hopefully we can get this merged in! I appreciate you taking the time to look at it!

**Comment by tbalz2319** [comment]
Hey just tried the code but i got the following error below:

```
"Creating 12 threads...

Exception in thread Thread-5:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "rapid.py", line 67, in worker
    subprocess_cmd(["/usr/bin/git", "clone", "https://github.com/{}.git".format(item)])
  File "rapid.py", line 57, in subprocess_cmd
    if "fatal" not in err:
TypeError: a bytes-like object is required, not 'str'"
```

**Comment by diego95root** [comment]
Oh, it must have something to do with python 3 syntax. I’m sorry, I work on python 2, so I wasn’t aware of the problem. I’ll look at it whenever I can.

**Comment by tbalz2319** [comment]
Awesome, thanks! Look forward to seeing it

**Comment by diego95root** [comment]
Okay this should do the job!

**Comment by tbalz2319** [comment]
Thanks! This looks great and worked really well!

**Pull request merged**
